### ISSUE TITLE
Client will fail to send report if attributes contain a null value

### ISSUE THREAD

**Issue by mk-ahmed-saucelabs** [backtrace-labs/backtrace-java#8]
This is easily reproduce-able by sending a report with attributes that contain some null value.

```
java.lang.NullPointerException: null
	at backtrace.io.data.Attributes.splitClientAttributes(Attributes.java:139)
	at backtrace.io.data.Attributes.<init>(Attributes.java:42)
	at backtrace.io.data.BacktraceData.setAttributes(BacktraceData.java:171)
	at backtrace.io.data.BacktraceData.<init>(BacktraceData.java:148)
	at backtrace.io.BacktraceQueueHandler.send(BacktraceQueueHandler.java:33)
	at backtrace.io.BacktraceClient.send(BacktraceClient.java:97)
	at backtrace.io.BacktraceClient.send(BacktraceClient.java:87)
```

**Comment by vlussenburg** [comment]
Thanks @mk-ahmed-saucelabs ! I'm getting this on the list to get fixed next release.

**Comment by vlussenburg** [comment]
Merged. Please keep an eye on our next release! Thanks!
