### ISSUE TITLE
Gson deserialization fails on jdk16+

### ISSUE THREAD

**Issue by mk-ahmed-saucelabs** [backtrace-labs/backtrace-java#9]
Starting from jdk16 it's no longer possible to use reflection to access private fields in certain conditions due to `strong encapsulation`. https://bugs.openjdk.org/browse/JDK-8256358 
Backtrace java uses Gson's reflection based type adapter. Hence the failure.

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @63db54ce
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:489)
	at com.google.gson.Gson.toJson(Gson.java:727)
	at com.google.gson.Gson.toJson(Gson.java:714)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:649)
	at backtrace.io.helpers.BacktraceSerializeHelper.toJson(BacktraceSerializeHelper.java:21)
	at backtrace.io.http.ApiSender.sendReport(ApiSender.java:29)
	at backtrace.io.Backtrace.sendReport(Backtrace.java:97)
	at backtrace.io.Backtrace.processSingleBacktraceMessage(Backtrace.java:74)
	at backtrace.io.Backtrace.handleBacktraceMessage(Backtrace.java:47)
	at backtrace.io.BacktraceThread.run(BacktraceThread.java:57)
```

**Comment by vlussenburg** [comment]
Thanks, added to our queue!

**Comment by vlussenburg** [comment]
@mk-ahmed-saucelabs could you include the steps to reproduce this?

**Comment by vlussenburg** [comment]
@mk-ahmed-saucelabs Thanks! PR created!
https://github.com/backtrace-labs/backtrace-java/pull/13

**Comment by BartoszLitwiniuk** [comment]
@mk-ahmed-saucelabs @vlussenburg fix was merged
